
name: Bitrise API

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-changes:
    runs-on: ubuntu-22.04

    steps:
      - name: Project Checkout
        uses: actions/checkout@v4.1.0

      - name: Check changes and deploy on bump.sh
        run: ./check-bitrise-api.sh ${{ secrets.BUMPSH_TOKEN }}

      - name: Create PR on changes
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          add-paths: bitrise-swagger.json
          commit-message: 'Updates Bitrise Swagger file'
          branch: 'gha/update-bitrise-swagger'
